import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

const myFont = localFont({ src: '../public/circular-spotify-text-font/CircularSpotifyText-Black.otf' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}